services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:7860"
    env_file:
      - .env.local
    environment:
      - FRONTEND_URL=http://localhost:3000
